{% set name = "betfairlightweight" %}
{% set version = "2.21.0" %}
{% set sha256 = "32e3178d90a5af26e6f75646d84349f3cd314dd9a2de599caac213f0d4ed3d8c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - requests <2.32.0
    - orjson >=3.9.4
    - ciso8601 >=2.3.0

test:
  requires:
    - mock
    - pip
    - python {{ python_min }}
  imports:
    - betfairlightweight
    - betfairlightweight.endpoints
    - betfairlightweight.resources
    - betfairlightweight.streaming
  source_files:
    - tests/*
    - HISTORY.rst
  commands:
    - python -m unittest discover -s tests --verbose
    - pip check

about:
  home: https://github.com/betcode-org/betfair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight python wrapper for Betfair API-NG

  description: |
    Lightweight, super fast pythonic wrapper for Betfair API-NG allowing all 
    betting operations (including market and order streaming) and most account operations.
  dev_url: https://github.com/betcode-org/betfair
extra:
  recipe-maintainers:
    - synapticarbors
    - liampauling
