{% set name = "betfairlightweight" %}
{% set version = "2.12.2" %}
{% set sha256 = "51b13aa91d2d46b6c525915168dd3f0cf95d536b00e67565742cb143e1c9415d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - orjson >=3.5.1
    - ciso8601 >=2.1.3

test:
  requires:
    - mock
  imports:
    - betfairlightweight
    - betfairlightweight.endpoints
    - betfairlightweight.resources
    - betfairlightweight.streaming
  source_files:
    - tests/*
  commands:
    - python -m unittest discover -s tests --verbose

about:
  home: https://github.com/liampauling/betfair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight python wrapper for Betfair API-NG

  description: |
    Lightweight, super fast pythonic wrapper for Betfair API-NG allowing all 
    betting operations (including market and order streaming) and most account operations.
  dev_url: https://github.com/liampauling/betfair
extra:
  recipe-maintainers:
    - synapticarbors
    - liampauling
