{% set name = "betfairlightweight" %}
{% set version = "1.0.0" %}
{% set sha256 = "81fd97ee6b498ebe3b4c630c0bb22d95325006f36f1b52d086f13c563193eecb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - requests
    - enum34  # [py<34]
  run:
    - python
    - requests
    - enum34  # [py<34]

test:
  requires:
    - mock
  imports:
    - betfairlightweight
    - betfairlightweight.endpoints
    - betfairlightweight.resources
    - betfairlightweight.streaming
  source_files:
    - tests/*
  commands:
    - python -m unittest discover -s tests --verbose

about:
  home: https://github.com/liampauling/betfairlightweight
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Lightweight python wrapper for Betfair API-NG'

  description: |
    Lightweight, super fast pythonic wrapper for Betfair API-NG allowing all 
    betting operations (including market and order streaming) and most account operations.
  dev_url: https://github.com/liampauling/betfairlightweight

extra:
  recipe-maintainers:
    - synapticarbors
    - liampauling
