{% set name = "betfairlightweight" %}
{% set version = "2.16.7" %}
{% set sha256 = "c9ac5dd32e0907ce679e0957a22df78873c1f05e4333d729478fe42c83cc94aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests <2.29.0
    - orjson >=3.7.7
    - ciso8601 >=2.2.0

test:
  requires:
    - mock
    - pip
  imports:
    - betfairlightweight
    - betfairlightweight.endpoints
    - betfairlightweight.resources
    - betfairlightweight.streaming
  source_files:
    - tests/*
    - HISTORY.rst
  commands:
    - python -m unittest discover -s tests --verbose
    - pip check

about:
  home: https://github.com/betcode-org/betfair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight python wrapper for Betfair API-NG

  description: |
    Lightweight, super fast pythonic wrapper for Betfair API-NG allowing all 
    betting operations (including market and order streaming) and most account operations.
  dev_url: https://github.com/betcode-org/betfair
extra:
  recipe-maintainers:
    - synapticarbors
    - liampauling
