{% set name = "betfairlightweight" %}
{% set version = "1.7.1" %}
{% set sha256 = "82c1fe1ff1a0406c66000d31b6be63462a0fdf32f04077f7ef8a654e09bdb807" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - enum34  # [py<34]
    - ujson >=1.35
    - ciso8601 >=2.0.0

test:
  requires:
    - mock
  imports:
    - betfairlightweight
    - betfairlightweight.endpoints
    - betfairlightweight.resources
    - betfairlightweight.streaming
  source_files:
    - tests/*
  commands:
    - python -m unittest discover -s tests --verbose

about:
  home: https://github.com/liampauling/betfair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Lightweight python wrapper for Betfair API-NG'

  description: |
    Lightweight, super fast pythonic wrapper for Betfair API-NG allowing all 
    betting operations (including market and order streaming) and most account operations.
  dev_url: https://github.com/liampauling/betfair
extra:
  recipe-maintainers:
    - synapticarbors
    - liampauling
