{% set name = "betfairlightweight" %}
{% set version = "2.0.0" %}
{% set sha256 = "d480456854cfef0ab0f0c264ca1192fe1a800e1ef77e06550c72046c53d41633" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [not py3k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - ujson >=1.35
    - ciso8601 >=2.1.3

test:
  requires:
    - mock
  imports:
    - betfairlightweight
    - betfairlightweight.endpoints
    - betfairlightweight.resources
    - betfairlightweight.streaming
  source_files:
    - tests/*
  commands:
    - python -m unittest discover -s tests --verbose

about:
  home: https://github.com/liampauling/betfair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Lightweight python wrapper for Betfair API-NG'

  description: |
    Lightweight, super fast pythonic wrapper for Betfair API-NG allowing all 
    betting operations (including market and order streaming) and most account operations.
  dev_url: https://github.com/liampauling/betfair
extra:
  recipe-maintainers:
    - synapticarbors
    - liampauling
