schema_version: 1

context:
  version: "2.24.0"

package:
  name: betfairlightweight
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/betfairlightweight/betfairlightweight-${{ version }}.tar.gz
  sha256: ce4238d25628db34380cc45598c0b5091efe4e29084875803d9489d4879d00df

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - requests <2.35.0
    - orjson >=3.12.04
    - ciso8601 >=2.3.3

tests:
  - python:
      imports:
        - betfairlightweight
        - betfairlightweight.endpoints
        - betfairlightweight.resources
        - betfairlightweight.streaming
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - tests/*
        - HISTORY.rst
    requirements:
      run:
        - mock
        - python ${{ python_min }}.*
    script:
      - python -m unittest discover -s tests --verbose

about:
  license: MIT
  license_file: LICENSE
  summary: Lightweight python wrapper for Betfair API-NG
  description: |
    Lightweight, super fast pythonic wrapper for Betfair API-NG allowing all
    betting operations (including market and order streaming) and most account operations.
  homepage: https://github.com/betcode-org/betfair
  repository: https://github.com/betcode-org/betfair

extra:
  recipe-maintainers:
    - synapticarbors
    - liampauling
