travis:
  secure:
    BINSTAR_TOKEN: dOlJMWsI7DLgKMxR7qYl4HW+IYTzURF6XXsv7lgFO/vtKJfxmPcUeN++rXgIv31s44Hj+0qY1DQRb66hLCYSnIraLDHeHHk2eH6MPWwRWETWa99+fOHHBeVMdX6mHzaVlMsAfxjMuEgnZcjdyfO3I3u0FqV/UNsKTaVxAC/KMWRAgUV+rVVN0IUeZloWtSoal5BDmzO1kyHpwY0Oon3AtkGWccNOzTjOazM6uYWQxDaYy54xGwXDi1Cka7+WnAVQZ0QIPVWDm8MXsyAtYf5CdPBzKNB+ujYFKx6Z6sIoFpMKLsujWzubK1icUsVM2pSQq3CoyjKEB1HqmDN+IPTLuzKeypqDDKvur6g2kj0T8R/sZW9RV/ZrXwQIe02JtynRdjVKd+cMiKXOENg6qX10lSyn3JoHo0tmpt3Bvm0HxYXlveuq013fz251yxP6iBKxyBLVBMdvLM/G5e0s5nX/gRJ3lUEAXWUZ81V9IXvyFpmDNH3qwD74//dkiO8W08M42kv/EgCfsOrf5P+qTr356ZBlFKR7vaBdkZKtAJv27CShnhotoybT/R98qhZNea6aCQwcBz+b8s1JnRphPLyhv0b8Xb8kF7Gq4oAlpRHmhb12RlNoOZQ6EXLANna8Pktt/JLs/THJsvvfLaicf5Nlw008HUOEXPs5h6aaWdBFpDY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
