travis:
  secure:
    BINSTAR_TOKEN: Ztmv1lXIg65Qms6X5qOhiExGrnjMXf/SXF9Hq9X2ZBpCL4FtRyabykuVSKRTXw2PLnRFE2IfOrruLnLnApENyS9PEgUlgOictPyNfdL5gql6eM7oGEtmqEN8Dtfb3Hlr2vkT19b09iXUZG5asPR9iwZo5B/YmN9Awupxuo+KjUeJeu7ij4RRfQkFzDbi69TV60mnhnCDL/JJp/M1kz8wNUUVdkgEzon+Zy6ebIjy15RzeRvo2DmUy1pxgcgpcHJlcd0XJbNNWYVuiWATMbpzDHE5fnRqV90DGdmdgtR11z3LOqSW+FFZKxUxNI/uDmuTV/dMehSt92Z1+BXNneUtdOMh/PSVGbEFkLA7OgxdC5a5Wna9gyI02YJgLzpJBValKOWmgoUiedXIcwO42RLeSo4jK08KxBhWdkzINTrpZNMqGL7HhRz5T0acIYQ3I3Z4YgxKeUHjFkfzbFJvpRQRjzpsVP0ZtiKMPY+D7ai40RAAmCMXLD/REgZwJ6FrVcs0wTWjmqZRfWLXbP7elV1gKGFA8Q7+XXwGlmHBATIqdPphsfDuzduYF5vcSIfeBjW+KmbryL+Vum2HEmIFQ1TY6XDkk2V4xKV0qQKdWTX9A7lNgxN1t0Y3EVovUo20yiuj+neX5iujlaxMiKjRCDBxJtU1u1zi0lZOavYlDTn+QE0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
